# This is a basic workflow to help you get started with Actions

name: CI Build Ubuntu Latest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Configure using CMake
    - name: Configuring
      run: cmake .

    # Build
    - name: Building
      run: make -j

      # Test Node
    - name: Testing Event.Grid Node
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND ./event.grid-node.test
          WORKING_DIRECTORY bin
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "event.grid-node.test tests failed!")
        endif()

      # Test Client C++
    - name: Testing Event.Grid C++ Client
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND ./event.grid-client.cpp.test
          WORKING_DIRECTORY bin
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "event.grid-client.cpp.test tests failed!")
        endif()

    # Test Client C
    - name: Testing Event.Grid C Client
      shell: cmake -P {0}
      run: |
        execute_process(
          COMMAND ./event.grid-client.c.test
          WORKING_DIRECTORY bin
          RESULT_VARIABLE result
        )
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "event.grid-client.c.test tests failed!")
        endif()
